// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgwcdaG8KRrDghF__7hUzehN-RcFD3pU',
    appId: '1:699354488894:web:e158a7ec85a8f99ee6b16f',
    messagingSenderId: '699354488894',
    projectId: 'eventapp-4df8e',
    authDomain: 'eventapp-4df8e.firebaseapp.com',
    storageBucket: 'eventapp-4df8e.firebasestorage.app',
    measurementId: 'G-BNF2WM1TES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQyXGoqL9B58-u0PcXwsLrQgLDmf8uNTI',
    appId: '1:699354488894:android:a7085e010ba969a3e6b16f',
    messagingSenderId: '699354488894',
    projectId: 'eventapp-4df8e',
    storageBucket: 'eventapp-4df8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtufPL_cjcpzpCJ_rDGR58AYS3C57LC1k',
    appId: '1:699354488894:ios:96dd2fa2900a290de6b16f',
    messagingSenderId: '699354488894',
    projectId: 'eventapp-4df8e',
    storageBucket: 'eventapp-4df8e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtufPL_cjcpzpCJ_rDGR58AYS3C57LC1k',
    appId: '1:699354488894:ios:96dd2fa2900a290de6b16f',
    messagingSenderId: '699354488894',
    projectId: 'eventapp-4df8e',
    storageBucket: 'eventapp-4df8e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTgwcdaG8KRrDghF__7hUzehN-RcFD3pU',
    appId: '1:699354488894:web:10672c3db7ca96e7e6b16f',
    messagingSenderId: '699354488894',
    projectId: 'eventapp-4df8e',
    authDomain: 'eventapp-4df8e.firebaseapp.com',
    storageBucket: 'eventapp-4df8e.firebasestorage.app',
    measurementId: 'G-TZT9P7N4MJ',
  );
}
